ssl_certificate /etc/nginx/cert/ygys30ds.crt;
ssl_certificate_key /etc/nginx/cert/ygys30ds.cloud.key;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:industry_ssl:10m;
ssl_session_timeout 1d;
